### ISSUE TITLE
Doesn't work?

### ISSUE THREAD

**Issue by hardyt** [NorthernSec/VeraCracker#1]
I tried a known password, but the program gives a false negative (i.e., the program said it tried the password and the password didn't work). Maybe I am using the command line incorrectly?

This is what I am trying:

python VeraCracker.py -v c:\temp\test2.tc -p list.txt -m I:

list.txt has six passwords in it, one on each line. One of the passwords is the correct password for c:\temp\test2.tc.

Also.. it goes through the passwords in a few ms. Way too quickly!

**Comment by PidgeyL** [comment]
Judging from the path (`c:\temp\test2.tc`) I'm assuming you're using Windows?
Are you using python 3.x, not python 2.x?
Do you have Veracrypt installed?

**Comment by hardyt** [comment]
I'm using Windows 7 Professional, Python 2.7.9, and VeraCrypt 1.0f-2. Does this require Python 3?

**Comment by PidgeyL** [comment]
Yes, it requires python 3 (see the readme)

-----Original Message-----

**Comment by hardyt** [comment]
Thanks for the hint and the quick responses. I'm now using Python 3.5. The volume mounts about three minutes after VeraCracker ends with this output, giving a false negative this time:

C:\Program Files (x86)\Python 3.5>python VeraCracker.py -v c:\temp\test2.tc -p list.txt -m I:
TODO: Is veracrypt installed
'query' is not recognized as an internal or external command, 
operable program or batch file.
'query' is not recognized as an internal or external command, 0/6
operable program or batch file.
'query' is not recognized as an internal or external command, 1/6
operable program or batch file.
'query' is not recognized as an internal or external command, 2/6
operable program or batch file.
'query' is not recognized as an internal or external command, 3/6
operable program or batch file.
'query' is not recognized as an internal or external command, 4/6
operable program or batch file.
'query' is not recognized as an internal or external command, 5/6
operable program or batch file.
Cracking [##################################################] 6/6
Password not found
Cracking duration: 0:00:00.280016
Passwords tried:   6

**Comment by PidgeyL** [comment]
yes, that is something I also noticed on some Windows computers. query is a cmd command that I used to see if a process is running. I remember another option, but I'd have to look for that again.

**Comment by hardyt** [comment]
Ok. Thanks for coding this!

**Comment by ferittuncer** [comment]
I fixed the issue which makes the script quit without trying all passwords.

**Comment by hardyt** [comment]
I still see the same output. On which Windows platform does this work?

**Comment by ferittuncer** [comment]
In Linux, works well. Your error seems related to something else.

**Comment by PidgeyL** [comment]
Yes. The issue is related to the "query" command in Windows. Not all versions support it, apparently. Not even amongst the same version. Might have to do with home/professional editions

**Comment by PidgeyL** [comment]
For windows users, check if you can find the query command, and if not, how to get it. for me, two out of three PC's had it, and because I'm mainly a Linux user, that was good enough for me :p

**Comment by bmweb75** [comment]
Hello PidgeyL, THANK YOU for this tool !
I am a Windows 10 user and I had the "query process" problem. (Python 3.7.2)
=> I replaced "query process" by "tasklist" (VeraWinProcList = "tasklist") to solving the problem.
=> I had to replace VeraWinProcName ="veracrypt.exe" by VeraWinProcName = "VeraCrypt.exe" to making the isVeraRunning() works.
And now your program works perfectly, it tests all the password of the *.txt file and find it (or not) and when found it mounts the drive and write the password that matches.
Thanks a lot for your work, I could recover files that I was trying to open since 2 years ;-)

**Comment by jns0x** [comment]
@bmweb75 
Thanks for that, script is running now, however it goes through password list too fast and even if there is correct password it will not tell it. Any sugesstions?
